parameters:
    app.encryption_key: '%env(APP_ENCRYPTION_KEY)%'
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Autowire tous les services du dossier src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Déclaration manuelle (ok si tu veux surcharger)
    App\Service\EncryptionService:
        arguments:
            $appEncryptionKey: '%app.encryption_key%'
